CREATE TABLE ti_gateway_provider (
  ti_gateway_provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  service_name VARCHAR(255) NOT NULL DEFAULT '',
  config_endpoint VARCHAR(255),
  active BOOLEAN,
  certificate BLOB,
  issuer VARCHAR(255),
  authorization_endpoint VARCHAR(255),
  token_endpoint VARCHAR(255),
  jwks_uri VARCHAR(255),
  response_types_supported VARCHAR(255),
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date TIMESTAMP,
  version BIGINT NOT NULL
);

CREATE UNIQUE INDEX service_name_idx ON ti_gateway_provider(service_name);
