package de.tsl.ingester.gatewayprovider.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

@JdbcTest
@Import(GatewayProviderBatchWriter.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class GatewayProviderBatchWriterTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private GatewayProviderBatchWriter gatewayProviderBatchWriter;

    @BeforeEach
    void createSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS ti_gateway_provider");
        jdbcTemplate.execute("""
            CREATE TABLE ti_gateway_provider (
              ti_gateway_provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(255) NOT NULL DEFAULT '',
              service_name VARCHAR(255) NOT NULL DEFAULT '',
              config_endpoint VARCHAR(255),
              active BOOLEAN,
              certificate BLOB,
              issuer VARCHAR(255),
              authorization_endpoint VARCHAR(255),
              token_endpoint VARCHAR(255),
              jwks_uri VARCHAR(255),
              response_types_supported VARCHAR(255),
              created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
              updated_date TIMESTAMP,
              version BIGINT NOT NULL
            )
            """);
        jdbcTemplate.execute("CREATE UNIQUE INDEX service_name_idx ON ti_gateway_provider(service_name)");
    }

    @Test
    void insertsUpdatesAndDeletesAtomically() {
        jdbcTemplate.update(
            """
            INSERT INTO ti_gateway_provider (
                name, service_name, config_endpoint, active, certificate, issuer,
                authorization_endpoint, token_endpoint, jwks_uri, response_types_supported, version
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            "Existing",
            "svc-existing",
            "https://existing.example",
            true,
            new byte[] { 0x01 },
            "old-issuer",
            "https://existing.example/auth",
            "https://existing.example/token",
            "https://existing.example/jwks",
            "code",
            1L
        );
        jdbcTemplate.update(
            """
            INSERT INTO ti_gateway_provider (
                name, service_name, config_endpoint, active, certificate, issuer,
                authorization_endpoint, token_endpoint, jwks_uri, response_types_supported, version
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            "Removed",
            "svc-removed",
            "https://removed.example",
            true,
            new byte[] { 0x02 },
            "removed-issuer",
            "https://removed.example/auth",
            "https://removed.example/token",
            "https://removed.example/jwks",
            "code",
            1L
        );

        GatewayProviderEntity insert = GatewayProviderEntity.rehydrate(
            null,
            "Inserted",
            "svc-inserted",
            "https://inserted.example",
            true,
            new byte[] { 0x03 },
            "issuer",
            "https://inserted.example/auth",
            "https://inserted.example/token",
            "https://inserted.example/jwks",
            "code,id_token",
            2L
        );
        GatewayProviderEntity update = GatewayProviderEntity.rehydrate(
            1L,
            "Updated Existing",
            "svc-existing",
            "https://existing.example",
            false,
            new byte[] { 0x04 },
            "issuer",
            "https://existing.example/auth",
            "https://existing.example/token",
            "https://existing.example/jwks",
            "code,id_token",
            2L
        );
        GatewayProviderEntity delete = GatewayProviderEntity.rehydrate(
            2L,
            "Removed",
            "svc-removed",
            "https://removed.example",
            false,
            new byte[] { 0x02 },
            "removed-issuer",
            "https://removed.example/auth",
            "https://removed.example/token",
            "https://removed.example/jwks",
            "code",
            2L
        );

        gatewayProviderBatchWriter.writeChanges(List.of(insert), List.of(update), List.of(delete));

        List<Map<String, Object>> rows = jdbcTemplate.queryForList(
            "SELECT service_name, active, issuer, response_types_supported, version, created_date, updated_date FROM ti_gateway_provider ORDER BY service_name"
        );

        assertThat(rows).hasSize(2);
        assertThat(rows).extracting(row -> row.get("service_name"))
            .containsExactly("svc-existing", "svc-inserted");
        assertThat(rows).allSatisfy(row -> assertThat(row.get("created_date")).isInstanceOf(Timestamp.class));
    }
}
